// Generated by scripts/build.mjs (esbuild). Do not edit directly.

// src/host/index.js
import { readFile as readFile2 } from "node:fs/promises";

// src/shared/notes.js
var KNOWN = {
  DEEPSEEK_API_KEY: "DeepSeek \u5E73\u53F0 API \u5BC6\u94A5\uFF08\u6A21\u578B\u8C03\u7528\uFF09",
  MOONSHOT_API_KEY: "Moonshot\uFF08\u6708\u4E4B\u6697\u9762\uFF09API \u5BC6\u94A5",
  OPENAI_API_KEY: "OpenAI API \u5BC6\u94A5"
};
var SUFFIXES = [
  [/_API_KEY$/, "API \u5BC6\u94A5"],
  [/_KEY$/, "\u5BC6\u94A5"],
  [/_ACCESS_TOKEN$/, "\u8BBF\u95EE\u4EE4\u724C"],
  [/_BOT_TOKEN$/, "\u673A\u5668\u4EBA\u4EE4\u724C"],
  [/_TOKEN$/, "\u4EE4\u724C"],
  [/_PASSWORD$/, "\u5BC6\u7801"],
  [/_PASSWD$/, "\u5BC6\u7801"],
  [/_PASS$/, "\u5BC6\u7801"],
  [/_SECRET$/, "\u5BC6\u94A5"],
  [/_PRIVATE_KEY$/, "\u79C1\u94A5"],
  [/_SSH_KEY$/, "SSH \u79C1\u94A5"],
  [/_HOSTNAME$/, "\u4E3B\u673A\u540D"],
  [/_HOST$/, "\u4E3B\u673A\u5730\u5740"],
  [/_USERNAME$/, "\u7528\u6237\u540D"],
  [/_USER$/, "\u7528\u6237\u540D"],
  [/_ENDPOINT$/, "\u63A5\u53E3\u5730\u5740"],
  [/_URL$/, "\u8BBF\u95EE\u5730\u5740"],
  [/_PORT$/, "\u7AEF\u53E3"],
  [/_DATABASE$/, "\u6570\u636E\u5E93\u540D"],
  [/_DB$/, "\u6570\u636E\u5E93"],
  [/_EMAIL$/, "\u90AE\u7BB1"],
  [/_ACCOUNT$/, "\u8D26\u53F7"],
  [/_ID$/, "\u6807\u8BC6"]
];
var BRANDS = {
  DEEPSEEK: "DeepSeek",
  MOONSHOT: "Moonshot",
  VPS: "VPS",
  DSH: "DSH",
  OPENAI: "OpenAI",
  GITHUB: "GitHub",
  ANTHROPIC: "Anthropic",
  WEIXIN: "\u5FAE\u4FE1"
};
function describeRef(name2) {
  const ref = String(name2 ?? "").trim();
  if (ref === "") return "";
  const known = KNOWN[ref];
  if (known !== void 0) return known;
  for (const [pattern, label] of SUFFIXES) {
    if (!pattern.test(ref)) continue;
    const owner = ref.replace(pattern, "");
    if (owner === "") return label;
    const words = owner.split("_").filter(Boolean).map((word) => BRANDS[word] ?? word);
    return `${words.join(" ")}${/^[A-Za-z]/.test(label) ? " \u7684 " : " \u7684"}${label}`;
  }
  return "";
}

// src/host/notes-file.js
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

// store-edit.mjs
var REF_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;
function isRefName(value) {
  return typeof value === "string" && REF_PATTERN.test(value);
}
function storePath(config) {
  if (config !== void 0 && typeof config.path === "string" && config.path.length > 0) return config.path;
  const home = process.env.DSH_HOME;
  if (typeof home === "string" && home.length > 0) return joinPath(home, ".credentials.yaml");
  return joinPath(process.env.HOME ?? process.env.USERPROFILE ?? ".", ".dsh", ".credentials.yaml");
}
function joinPath(...parts) {
  return parts.join("/").replace(/\/{2,}/g, "/");
}
function parseRefNames(text, section = "refs") {
  const names = [];
  const seen = /* @__PURE__ */ new Set();
  let inRefs = false;
  for (const line of text.split(/\r?\n/)) {
    if (!inRefs) {
      if (new RegExp(`^${section}:\\s*$`).test(line)) inRefs = true;
      continue;
    }
    if (/^\S/.test(line)) break;
    if (/^\s*$/.test(line) || /^\s*#/.test(line)) continue;
    const match = /^ {2}([A-Za-z_][A-Za-z0-9_]*):(\s|$)/.exec(line);
    if (match !== null && !seen.has(match[1])) {
      seen.add(match[1]);
      names.push(match[1]);
    }
  }
  return names;
}
var TOP_LEVEL_KNOWN = /^(version:|refs:|notes:|records:|\s|#|$)/;
function assertEditable(text) {
  if (text.trim().length === 0) return;
  for (const line of text.split(/\r?\n/)) {
    if (!TOP_LEVEL_KNOWN.test(line)) {
      throw new Error(`\u5B58\u50A8\u6587\u6863\u91CC\u6709\u672C\u5DE5\u5177\u4E0D\u8BA4\u8BC6\u7684\u9876\u5C42\u5185\u5BB9\uFF0C\u62D2\u7EDD\u6539\u5199\uFF1A${JSON.stringify(line.slice(0, 60))}`);
    }
  }
}
function quoteScalar(value) {
  if (typeof value !== "string" || value.length === 0) throw new Error("\u5BC6\u7801\u4E0D\u80FD\u4E3A\u7A7A\uFF08\u5220\u9664\u6761\u76EE\u8BF7\u7528 del\uFF09");
  if (/[\r\n]/.test(value)) throw new Error("\u5BC6\u7801\u91CC\u542B\u6362\u884C\uFF1A\u672C\u5DE5\u5177\u53EA\u5199\u5355\u884C\u6807\u91CF\uFF0C\u591A\u884C\u5185\u5BB9\u8BF7\u6539\u7528\u5BC6\u94A5\u6587\u4EF6");
  return `'${value.replace(/'/g, "''")}'`;
}
function sectionRange(lines, key) {
  const head = new RegExp(`^${key}:\\s*$`);
  const start = lines.findIndex((line) => head.test(line));
  if (start === -1) return void 0;
  let end = lines.length;
  for (let index = start + 1; index < lines.length; index += 1) {
    if (/^\S/.test(lines[index])) {
      end = index;
      break;
    }
  }
  return { start, end };
}
function toLines(text) {
  const lines = text.split(/\r?\n/);
  if (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines;
}
function setRefValue(text, name2, value, section = "refs") {
  if (!isRefName(name2)) throw new Error(`\u51ED\u636E\u540D\u4E0D\u5408\u6CD5\uFF1A${JSON.stringify(name2)}\uFF08\u987B\u5339\u914D ${String(REF_PATTERN)}\uFF09`);
  const entry = `  ${name2}: ${quoteScalar(value)}`;
  const lines = toLines(text);
  const range = sectionRange(lines, section);
  if (range === void 0) {
    const out = [...lines];
    if (out.length > 0 && out[out.length - 1].trim() !== "") out.push("");
    out.push(`${section}:`, entry);
    return `${out.join("\n")}
`;
  }
  const head = new RegExp(`^ {2}${name2}:`);
  const at = lines.findIndex((line, index) => index > range.start && index < range.end && head.test(line));
  if (at !== -1) {
    lines[at] = entry;
    return `${lines.join("\n")}
`;
  }
  let insertAt = range.start + 1;
  for (let index = range.start + 1; index < range.end; index += 1) {
    if (lines[index].trim() !== "") insertAt = index + 1;
  }
  lines.splice(insertAt, 0, entry);
  return `${lines.join("\n")}
`;
}
function deleteRef(text, name2, section = "refs") {
  if (!isRefName(name2)) throw new Error(`\u51ED\u636E\u540D\u4E0D\u5408\u6CD5\uFF1A${JSON.stringify(name2)}\uFF08\u987B\u5339\u914D ${String(REF_PATTERN)}\uFF09`);
  const lines = toLines(text);
  const range = sectionRange(lines, section);
  if (range === void 0) return { text, removed: false };
  const head = new RegExp(`^ {2}${name2}:`);
  const at = lines.findIndex((line, index) => index > range.start && index < range.end && head.test(line));
  if (at === -1) return { text, removed: false };
  const from = at > range.start + 1 && /^ {2}#/.test(lines[at - 1]) ? at - 1 : at;
  lines.splice(from, at - from + 1);
  return { text: `${lines.join("\n")}
`, removed: true };
}

// src/host/notes-file.js
var HEADER = "# dsh-secret\uFF1A\u51ED\u636E\u7684\u4E2D\u6587\u8BF4\u660E\uFF08\u952E\u662F\u51ED\u636E\u540D\uFF0C\u503C\u662F\u8BF4\u660E\u6587\u5B57\uFF1B\u8FD9\u91CC\u4E0D\u542B\u4EFB\u4F55\u5BC6\u7801\uFF09\nversion: 1\n";
function unquoteScalar(raw) {
  const text = raw.trim();
  if (text.length >= 2 && text.startsWith("'") && text.endsWith("'")) {
    return text.slice(1, -1).replace(/''/g, "'");
  }
  if (text.length >= 2 && text.startsWith('"') && text.endsWith('"')) return text.slice(1, -1);
  return text;
}
function notesPathOf(options) {
  if (typeof options?.notesPath === "string" && options.notesPath.length > 0) return options.notesPath;
  return join(dirname(storePath(options ?? {})), ".credentials-notes.yaml");
}
async function readNotes(path) {
  let text;
  try {
    text = await readFile(path, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return /* @__PURE__ */ new Map();
    throw error;
  }
  const notes = /* @__PURE__ */ new Map();
  let inNotes = false;
  for (const line of text.split(/\r?\n/)) {
    if (!inNotes) {
      if (/^notes:\s*$/.test(line)) inNotes = true;
      continue;
    }
    if (/^\S/.test(line)) break;
    if (/^\s*$/.test(line) || /^\s*#/.test(line)) continue;
    const match = /^ {2}([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$/.exec(line);
    if (match !== null) notes.set(match[1], unquoteScalar(match[2]));
  }
  return notes;
}
async function mutate(path, change) {
  let text = "";
  try {
    text = await readFile(path, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  if (text.trim() === "") text = HEADER;
  assertEditable(text);
  const next = change(text);
  await mkdir(dirname(path), { recursive: true });
  const temporary = `${path}.tmp-${String(process.pid)}`;
  await writeFile(temporary, next, { mode: 384 });
  await rename(temporary, path);
}
async function writeNote(path, ref, note) {
  await mutate(path, (current) => {
    if (note === "") return current.includes("notes:") ? deleteRef(current, ref, "notes").text : current;
    return setRefValue(current, ref, note, "notes");
  });
}
async function renameNote(path, from, to) {
  const notes = await readNotes(path);
  if (!notes.has(from)) return;
  const label = notes.get(from);
  await mutate(path, (current) => setRefValue(deleteRef(current, from, "notes").text, to, label, "notes"));
}
async function deleteNote(path, ref) {
  const notes = await readNotes(path);
  if (!notes.has(ref)) return;
  await mutate(path, (current) => deleteRef(current, ref, "notes").text);
}

// src/host/index.js
var SECRET_ENV = "DSH_SECRET";
var REDACTED = "\xAB\u5DF2\u5C4F\u853D\xBB";
var MIN_REDACTABLE_LENGTH = 4;
var name = "secret";
var inject = ["tools"];
var approvedSessions = /* @__PURE__ */ new Set();
function redact(text, secret) {
  if (typeof secret !== "string" || secret.length < MIN_REDACTABLE_LENGTH) return text;
  return text.split(secret).join(REDACTED);
}
function resolveOptions(config) {
  const approval = config !== void 0 && config.approval === "never" ? "never" : "always";
  const allow = config !== void 0 && Array.isArray(config.allow) ? config.allow.filter((entry) => isRefName(entry)) : [];
  return { path: storePath(config), approval, allow };
}
function sessionKeyOf(exec) {
  const id = exec?.agent?.session?.id;
  return typeof id === "string" && id.length > 0 ? id : void 0;
}
async function readRefNames(path) {
  let text;
  try {
    text = await readFile2(path, "utf8");
  } catch (error) {
    if (error !== null && typeof error === "object" && error.code === "ENOENT") return [];
    throw error;
  }
  return parseRefNames(text);
}
async function readRows(ctx, options) {
  const credentials = ctx.get("credentials");
  const names = await readRefNames(options.path);
  const notes = await readNotes(notesPathOf(options));
  const rows = [];
  for (const name2 of names) {
    let info = { configured: false, writable: false };
    if (credentials !== void 0) info = await credentials.describe(name2);
    rows.push({
      name: name2,
      // The stored label wins; the derived one keeps an unlabelled store readable.
      note: notes.get(name2) ?? describeRef(name2),
      configured: info.configured === true,
      ...info.source === void 0 ? {} : { source: info.source },
      writable: info.writable === true
    });
  }
  return rows;
}
function requireCredentials(ctx) {
  const credentials = ctx.get("credentials");
  if (credentials === void 0) throw new Error("\u672C\u7EC4\u5408\u6CA1\u6709\u6302\u8F7D\u51ED\u636E\u670D\u52A1\uFF08ctx.credentials\uFF09");
  return credentials;
}
function listTool(ctx, options) {
  return {
    name: "secret_list",
    description: "List the credential names saved in this machine's DSH credential store, with a value-free status (configured / source layer / writable). Use it to learn which names you may reference with secret_run. It never returns a secret value, and it needs no approval.",
    parameters: { type: "object", properties: {}, additionalProperties: false },
    output: {
      schema: {
        type: "object",
        properties: {
          refs: {
            type: "array",
            items: {
              type: "object",
              properties: {
                name: { type: "string" },
                configured: { type: "boolean" },
                source: { type: "string" },
                writable: { type: "boolean" },
                note: { type: "string" }
              },
              required: ["name", "configured", "writable"],
              additionalProperties: false
            }
          }
        },
        required: ["refs"],
        additionalProperties: false
      },
      render(_args, value) {
        const rows = Array.isArray(value?.refs) ? value.refs : [];
        if (rows.length === 0) {
          return [{ type: "text", text: "\u51ED\u636E\u5B58\u50A8\u91CC\u6CA1\u6709\u4EFB\u4F55\u6761\u76EE\uFF08\u6216\u5B58\u50A8\u6587\u4EF6\u4E0D\u5B58\u5728\uFF09\u3002" }];
        }
        const lines = rows.map((row) => {
          const state = row.configured ? "\u5DF2\u914D\u7F6E" : "\u672A\u914D\u7F6E";
          const source = row.source === void 0 ? "" : ` \xB7 \u6765\u6E90 ${row.source}`;
          const readOnly = row.writable === false ? " \xB7 \u53EA\u8BFB\uFF08\u88AB\u542F\u52A8\u73AF\u5883\u906E\u853D\uFF09" : "";
          const note = typeof row.note === "string" && row.note !== "" ? row.note : describeRef(row.name);
          return `- ${row.name}${note === "" ? "" : ` \u2014 ${note}`} \xB7 ${state}${source}${readOnly}`;
        });
        return [{ type: "text", text: `\u5171 ${rows.length} \u6761\u51ED\u636E\uFF08\u53EA\u5217\u540D\u5B57\uFF0C\u4E0D\u542B\u503C\uFF09\uFF1A
${lines.join("\n")}` }];
      }
    },
    async execute() {
      return { refs: await readRows(ctx, options) };
    }
  };
}
function runTool(ctx, options) {
  return {
    name: "secret_run",
    description: 'Run one shell command with a stored secret injected into its environment, and return stdout/stderr/exit code with every occurrence of the secret redacted. The value is never returned and never needs to appear in the conversation: reference it inside the command as $DSH_SECRET or as the credential\'s own name (e.g. "$DB_PASSWORD"). The first such call in a session asks the user for approval. Prefer tools that read the secret from the environment (e.g. `sshpass -e` with an inline SSHPASS assignment); never put it in an argv position, where `ps` would expose it.',
    parameters: {
      type: "object",
      properties: {
        ref: {
          type: "string",
          description: "Credential name, matching [A-Za-z_][A-Za-z0-9_]* \u2014 e.g. DB_PASSWORD. Call secret_list for the available names."
        },
        command: {
          type: "string",
          description: 'Shell command to execute. Reference the secret as "$DSH_SECRET" or "$<ref>" (the name you passed).'
        },
        timeoutMs: {
          type: "number",
          description: "Optional timeout in milliseconds; the executor caps it."
        }
      },
      required: ["ref", "command"],
      additionalProperties: false
    },
    output: {
      schema: {
        type: "object",
        properties: {
          ref: { type: "string" },
          exitCode: { oneOf: [{ type: "integer" }, { type: "null" }] },
          signal: { oneOf: [{ type: "string" }, { type: "null" }] },
          timedOut: { type: "boolean" },
          stdout: { type: "string" },
          stderr: { type: "string" },
          truncated: { type: "boolean" }
        },
        required: ["ref", "exitCode", "signal", "timedOut", "stdout", "stderr", "truncated"],
        additionalProperties: false
      },
      render(_args, value) {
        const status = value?.exitCode === null ? `killed by signal ${String(value?.signal)}` : `exit code ${String(value?.exitCode)}`;
        const refName = String(value?.ref ?? "");
        const parts = [`[${status}] (${refName} injected as $${SECRET_ENV} and $${refName}, value redacted)`];
        const stdout = String(value?.stdout ?? "");
        const stderr = String(value?.stderr ?? "");
        if (stdout.length > 0) parts.push(`--- stdout ---
${stdout.replace(/\n+$/, "")}`);
        if (stderr.length > 0) parts.push(`--- stderr ---
${stderr.replace(/\n+$/, "")}`);
        if (value?.truncated === true) parts.push("(output truncated by the executor)");
        return [{ type: "text", text: parts.join("\n") }];
      }
    },
    async execute(args, exec) {
      const ref = typeof args?.ref === "string" ? args.ref : "";
      const command = typeof args?.command === "string" ? args.command : "";
      if (!isRefName(ref)) {
        throw new Error(`\u51ED\u636E\u540D\u4E0D\u5408\u6CD5\uFF1A${JSON.stringify(ref)}\uFF08\u987B\u5339\u914D [A-Za-z_][A-Za-z0-9_]*\uFF09`);
      }
      if (command.trim().length === 0) throw new Error("command \u4E0D\u80FD\u4E3A\u7A7A");
      if (options.allow.length > 0 && !options.allow.includes(ref)) {
        throw new Error(`\u51ED\u636E ${ref} \u4E0D\u5728\u672C\u63D2\u4EF6\u5141\u8BB8\u7684\u540D\u5B57\u91CC\uFF08allow: ${options.allow.join(", ")}\uFF09`);
      }
      const session = sessionKeyOf(exec);
      if (session !== void 0) approvedSessions.add(session);
      const resolved = await requireCredentials(ctx).resolve(ref);
      if (resolved === void 0) {
        throw new Error(`\u51ED\u636E ${ref} \u672A\u914D\u7F6E\uFF08\u7528 secret_list \u770B\u5DF2\u5B58\u6761\u76EE\uFF0C\u6216\u5728\u201C\u5BC6\u7801\u7BA1\u7406\u201D\u9762\u677F\u91CC\u52A0\u4E00\u6761\uFF09`);
      }
      const shell = ctx.get("shell");
      if (shell === void 0) throw new Error("\u672C\u7EC4\u5408\u6CA1\u6709\u6302\u8F7D shell \u670D\u52A1\uFF08ctx.shell\uFF09");
      const timeoutMs = typeof args?.timeoutMs === "number" && Number.isFinite(args.timeoutMs) && args.timeoutMs > 0 ? args.timeoutMs : void 0;
      const env = { [SECRET_ENV]: resolved.value };
      if (ref !== SECRET_ENV) env[ref] = resolved.value;
      const policyService = ctx.get("sandboxPolicy");
      const sandboxPolicy = policyService === void 0 ? void 0 : policyService.resolve(exec?.agent === void 0 ? {} : { session: exec.agent.session });
      const result = await shell.run(shell.resolve({
        command,
        env,
        ...timeoutMs === void 0 ? {} : { timeoutMs },
        ...sandboxPolicy === void 0 ? {} : { sandboxPolicy },
        ...exec?.signal === void 0 ? {} : { signal: exec.signal }
      }));
      const stdout = redact(result.stdout.text, resolved.value);
      const stderr = redact(result.stderr.text, resolved.value);
      return {
        ref,
        exitCode: result.exitCode,
        signal: result.signal,
        timedOut: result.timedOut === true,
        stdout,
        stderr,
        truncated: result.stdout.truncated === true || result.stderr.truncated === true
      };
    }
  };
}
function createService(ctx, options) {
  return {
    /** Every stored name with its value-free status. */
    async list() {
      return { refs: await readRows(ctx, options) };
    },
    /**
     * Store or replace one credential.
     * @param ref - credential name.
     * @param value - the secret; never echoed back.
     */
    async set(ref, value, note) {
      if (!isRefName(ref)) {
        throw new Error(`\u51ED\u636E\u540D\u4E0D\u5408\u6CD5\uFF1A${JSON.stringify(ref)}\uFF08\u987B\u5339\u914D [A-Za-z_][A-Za-z0-9_]*\uFF09`);
      }
      if (typeof value !== "string" || value.length === 0) {
        throw new Error("\u5BC6\u7801\u4E0D\u80FD\u4E3A\u7A7A\uFF08\u8981\u5220\u9664\u6761\u76EE\u8BF7\u7528\u5220\u9664\uFF09");
      }
      await requireCredentials(ctx).set(ref, value);
      if (typeof note === "string") await writeNote(notesPathOf(options), ref, note.trim());
      return { refs: await readRows(ctx, options) };
    },
    /**
     * Remove one credential.
     *
     * Named `unset`, not `remove`: the Remote namespace runtime reserves
     * `remove` on its own service object and rejects a contribution that uses
     * the name (the client mount fails with "conflicts with its namespace
     * service"). This also matches the credential seam's own `unset`.
     * @param ref - credential name.
     */
    async unset(ref) {
      if (!isRefName(ref)) {
        throw new Error(`\u51ED\u636E\u540D\u4E0D\u5408\u6CD5\uFF1A${JSON.stringify(ref)}\uFF08\u987B\u5339\u914D [A-Za-z_][A-Za-z0-9_]*\uFF09`);
      }
      await requireCredentials(ctx).unset(ref);
      await deleteNote(notesPathOf(options), ref);
      return { refs: await readRows(ctx, options) };
    },
    /**
     * Store or clear one credential's Chinese label.
     * @param ref - credential name; it must already exist.
     * @param note - the label; `''` restores the derived fallback.
     */
    async setNote(ref, note) {
      if (!isRefName(ref)) {
        throw new Error(`\u51ED\u636E\u540D\u4E0D\u5408\u6CD5\uFF1A${JSON.stringify(ref)}\uFF08\u987B\u5339\u914D [A-Za-z_][A-Za-z0-9_]*\uFF09`);
      }
      const names = await readRefNames(options.path);
      if (!names.includes(ref)) throw new Error(`\u51ED\u636E ${ref} \u4E0D\u5B58\u5728\uFF0C\u5148\u65B0\u589E\u518D\u6539\u8BF4\u660E`);
      await writeNote(notesPathOf(options), ref, String(note ?? "").trim());
      return { refs: await readRows(ctx, options) };
    },
    /**
     * Rename one credential, value and label together.
     *
     * The value is read and rewritten host-side, so renaming never exposes it to
     * the browser — this is the one operation the panel cannot do with set/unset.
     * @param from - current credential name.
     * @param to - new credential name.
     */
    async rename(from, to) {
      if (!isRefName(from) || !isRefName(to)) {
        throw new Error(`\u51ED\u636E\u540D\u4E0D\u5408\u6CD5\uFF08\u987B\u5339\u914D [A-Za-z_][A-Za-z0-9_]*\uFF09\uFF1A${JSON.stringify({ from, to })}`);
      }
      if (from === to) return { refs: await readRows(ctx, options) };
      const names = await readRefNames(options.path);
      if (!names.includes(from)) throw new Error(`\u51ED\u636E ${from} \u4E0D\u5B58\u5728`);
      if (names.includes(to)) throw new Error(`\u76EE\u6807\u540D\u5B57 ${to} \u5DF2\u5B58\u5728\uFF0C\u8BF7\u6362\u4E00\u4E2A`);
      const credentials = requireCredentials(ctx);
      const resolved = await credentials.resolve(from);
      if (resolved === void 0) throw new Error(`\u51ED\u636E ${from} \u6CA1\u6709\u53EF\u8BFB\u53D6\u7684\u503C\uFF08\u53EF\u80FD\u7531\u542F\u52A8\u73AF\u5883\u63D0\u4F9B\uFF0C\u65E0\u6CD5\u6539\u540D\uFF09`);
      await credentials.set(to, resolved.value);
      await credentials.unset(from);
      await renameNote(notesPathOf(options), from, to);
      return { refs: await readRows(ctx, options) };
    }
  };
}
function apply(ctx, config) {
  try {
    mount(ctx, config);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    try {
      ctx.logger?.error?.(`dsh-secret: activation failed, plugin not mounted: ${message}`);
    } catch {
    }
  }
}
function mount(ctx, config) {
  const options = resolveOptions(config);
  ctx.effect(() => ctx.tools.register(listTool(ctx, options)), "secret: secret_list");
  ctx.effect(() => ctx.tools.register(runTool(ctx, options)), "secret: secret_run");
  const service = createService(ctx, options);
  Object.defineProperty(service, "typertRemote", {
    configurable: false,
    enumerable: false,
    writable: false,
    value: { service, serviceKey: "secretManager", namespace: "secretManager" }
  });
  ctx.provide("secretManager", service);
  if (options.approval === "never") return;
  ctx.effect(() => ctx.on("tools/pre-execute", async (exec, next) => {
    if (exec === void 0 || exec.name !== "secret_run") return next();
    const session = sessionKeyOf(exec);
    if (session !== void 0 && approvedSessions.has(session)) return next();
    const args = exec.arguments;
    const ref = args !== null && typeof args === "object" && typeof args.ref === "string" ? args.ref : "(\u672A\u6307\u5B9A)";
    return {
      kind: "ask",
      reason: `dsh-secret\uFF1A\u672C\u4F1A\u8BDD\u9996\u6B21\u4F7F\u7528\u51ED\u636E ${ref} \u6267\u884C\u547D\u4EE4\uFF08\u503C\u6CE8\u5165\u5B50\u8FDB\u7A0B\uFF0C\u8F93\u51FA\u5DF2\u8131\u654F\uFF09\u3002\u786E\u8BA4\u540E\u672C\u4F1A\u8BDD\u4E0D\u518D\u8BE2\u95EE\u3002`
    };
  }), "secret: approval gate");
  ctx.effect(() => () => {
    approvedSessions.clear();
  }, "secret: approval ledger");
}
export {
  apply,
  createService,
  inject,
  name,
  redact,
  resolveOptions,
  sessionKeyOf
};
