// Generated by scripts/build.mjs (esbuild). Do not edit directly.

// src/shared/wire.js
import { z } from "zod";
function codec(typeSymbol, schema) {
  return { mode: "strict", typeSymbol: `dsh-secret#${typeSymbol}`, schema };
}
var refRowSchema = z.object({
  name: z.string(),
  configured: z.boolean(),
  source: z.string().optional(),
  writable: z.boolean(),
  /** Chinese label: the stored one, else the derived fallback. */
  note: z.string()
});
var refListSchema = z.object({ refs: z.array(refRowSchema) });
var refListCodec = codec("RefList", refListSchema);
var refNameCodec = codec("RefName", z.string());
var secretValueCodec = codec("SecretValue", z.string());
var noteCodec = codec("Note", z.string());
var INVOCATIONS = [
  {
    id: "dsh-secret#secretManager/list",
    service: "secretManager",
    namespace: "secretManager",
    method: "list",
    invocation: { kind: "direct" },
    parameters: [],
    result: refListCodec
  },
  {
    id: "dsh-secret#secretManager/set",
    service: "secretManager",
    namespace: "secretManager",
    method: "set",
    invocation: { kind: "direct" },
    parameters: [
      { name: "ref", wire: "ref", source: "json", codec: refNameCodec },
      { name: "value", wire: "value", source: "json", codec: secretValueCodec },
      { name: "note", wire: "note", source: "json", codec: noteCodec }
    ],
    result: refListCodec
  },
  {
    id: "dsh-secret#secretManager/unset",
    service: "secretManager",
    namespace: "secretManager",
    method: "unset",
    invocation: { kind: "direct" },
    parameters: [{ name: "ref", wire: "ref", source: "json", codec: refNameCodec }],
    result: refListCodec
  },
  {
    id: "dsh-secret#secretManager/setNote",
    service: "secretManager",
    namespace: "secretManager",
    method: "setNote",
    invocation: { kind: "direct" },
    parameters: [
      { name: "ref", wire: "ref", source: "json", codec: refNameCodec },
      { name: "note", wire: "note", source: "json", codec: noteCodec }
    ],
    result: refListCodec
  },
  {
    id: "dsh-secret#secretManager/rename",
    service: "secretManager",
    namespace: "secretManager",
    method: "rename",
    invocation: { kind: "direct" },
    parameters: [
      { name: "from", wire: "from", source: "json", codec: refNameCodec },
      { name: "to", wire: "to", source: "json", codec: refNameCodec }
    ],
    result: refListCodec
  }
];

// src/host/typert.js
var TYPERT = {
  package: "dsh-secret",
  face: "host",
  schemas: [],
  invocations: INVOCATIONS,
  model: {
    services: [
      {
        key: "secretManager",
        exportName: "secretManager",
        description: "\u5BC6\u94A5\u7BA1\u7406:\u5217\u51FA\u3001\u5199\u5165\u3001\u6539\u540D\u3001\u5220\u9664\u672C\u673A\u51ED\u636E\u5B58\u50A8\u91CC\u7684\u6761\u76EE,\u5E76\u7EF4\u62A4\u5B83\u4EEC\u7684\u4E2D\u6587\u8BF4\u660E(\u6C38\u4E0D\u56DE\u503C)\u3002",
        summary: "List, store, rename, and remove credential-store entries, and edit their Chinese labels, for the management panel. Values never cross the wire.",
        jsDoc: "/** Credential-store management service behind the `secretManager` Remote namespace. */",
        tags: ["credentials", "secrets", "web"],
        members: [
          { name: "list", kind: "method", signature: "list(): Promise<RefList>" },
          { name: "set", kind: "method", signature: "set(ref: string, value: string, note: string): Promise<RefList>" },
          { name: "setNote", kind: "method", signature: "setNote(ref: string, note: string): Promise<RefList>" },
          { name: "rename", kind: "method", signature: "rename(from: string, to: string): Promise<RefList>" },
          { name: "unset", kind: "method", signature: "unset(ref: string): Promise<RefList>" }
        ],
        types: []
      }
    ],
    events: [],
    objects: []
  }
};
var typert_default = TYPERT;
export {
  TYPERT,
  typert_default as default
};
