/**
 * Build dsh-secret.
 *
 * Four artifacts:
 *   - lib/index.js       Host half (Node ESM bundle).
 *   - lib/typert.host.js Hand-written Typert manifest (zod stays external).
 *   - lib/client.js      Browser half, wrapped in the DSH lazy-CJS module
 *                        loader envelope the client module system expects.
 *
 * `zod` is the host bundle's only external; `react` and `react-dom` are the
 * browser bundle's, seeded into the shared module table by the runtime.
 */

import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const lib = join(root, 'lib')

const BANNER = {
  js: '// Generated by scripts/build.mjs (esbuild). Do not edit directly.',
}

const CLIENT_EXTERNALS = ['react', 'react-dom']

async function main() {
  await mkdir(lib, { recursive: true })

  await build({
    entryPoints: [join(root, 'src/host/index.js')],
    outfile: join(lib, 'index.js'),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    external: ['zod'],
    banner: BANNER,
    logLevel: 'warning',
  })

  await build({
    entryPoints: [join(root, 'src/host/typert.js')],
    outfile: join(lib, 'typert.host.js'),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    external: ['zod'],
    banner: BANNER,
    logLevel: 'warning',
  })

  const temporaryClient = join(lib, '.client.cjs')
  await build({
    entryPoints: [join(root, 'src/client/index.jsx')],
    outfile: temporaryClient,
    bundle: true,
    platform: 'browser',
    format: 'cjs',
    target: 'es2022',
    jsx: 'transform',
    external: CLIENT_EXTERNALS,
    define: { 'process.env.NODE_ENV': '"production"' },
    legalComments: 'none',
    logLevel: 'warning',
  })

  const body = await readFile(temporaryClient, 'utf8')
  await rm(temporaryClient)
  await writeFile(join(lib, 'client.js'), [
    '// Generated by scripts/build.mjs (esbuild). Do not edit directly.',
    'window.__ModuleLoader__.load({',
    'id: "dsh-secret",',
    'factory: (require) => {',
    'var module = { exports: {} };',
    'var exports = module.exports;',
    body,
    'return module.exports;',
    '},',
    '});',
    '',
  ].join('\n'))

  process.stdout.write('dsh-secret: built lib/index.js, lib/typert.host.js, lib/client.js\n')
}

await main()
